# Generated by Django 5.0.9 on 2024-10-11 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('moduleid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('modulename', models.CharField(max_length=30)),
                ('prompt', models.TextField(max_length=1000)),
                ('voice', models.CharField(max_length=50)),
                ('system_prompt', models.TextField(max_length=1000)),
                ('case_abstract', models.TextField(max_length=200)),
                ('file', models.TextField(blank=True, max_length=200, null=True)),
                ('model', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interviewid', models.AutoField(primary_key=True, serialize=False)),
                ('dateactive', models.DateTimeField()),
                ('interviewlength', models.DurationField()),
                ('transcript', models.TextField()),
                ('moduleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.module')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.users')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('moduleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.module')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.users')),
            ],
        ),
    ]
