# Generated by Django 5.0.9 on 2024-10-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_alter_users_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='last_login',
        ),
    ]
