# Generated by Django 5.0.9 on 2024-10-13 00:03

import django.db.models.deletion
import interview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_remove_users_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='adminid',
            field=models.CharField(default=interview.models.generate_userid, editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='moduleid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.module'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='admin',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='userid',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
