# Generated by Django 5.0.9 on 2024-10-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_users_is_admin_users_is_superuser_alter_module_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='timestamps',
            field=models.JSONField(default=list),
        ),
    ]
