# Generated by Django 5.0.9 on 2024-10-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0016_alter_module_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='file',
            field=models.JSONField(default=list),
        ),
    ]
